server:
  port: 8031

spring:
  flyway:
    baseline-on-migrate: false # 线上可能由于DDL权限等问题，需要关闭flyway功能
    baseline-version: 0
  # DB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flow_job?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false  # 日志中显示sql语句
    properties:
      hibernate:
        enable_lazy_load_no_trans: true # 解决懒加载问题 no Session

flowjob:
  agent:
    enabled: false
    auto-start: false
    brokers:
      - http://localhost:8081
    datasource-url: jdbc:h2:mem:flowjob_db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=mysql;
    #    datasource-url: jdbc:h2:file:/Users/devil/h2/flowjob_db;AUTO_SERVER=true;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=mysql;
    init-table: true


