server:
  port: 8085
spring:
  application:
    name: flowjob-worker

# log
logging:
  config: classpath:log4j2.xml

flowjob:
  worker:
    brokers:
      - http://localhost:8081
    queue-size: 64
    tags:
      - a=b
      - c=d
    auto-register: true
