spring:
  profiles:
    active: dev

  application:
    name: flowjob-broker

# log
logging:
  config: classpath:log4j2.xml

# 配置 https://springdoc.org/#springdoc-openapi-core-properties
# 注解 https://springdoc.org/#migrating-from-springfox
# 访问 http://server:port/api-docs.html
springdoc:
  swagger-ui:
    path: /api-docs.html
  api-docs:
    path: /api-docs
#  group-configs:
#    - group: admin
#      pathsToMatch: /api/admin/**
#    - group: sdk
#      pathsToMatch: /api/sdk/**
